# Generated by Django 4.2.7 on 2024-06-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='videos',
            field=models.URLField(blank=True, null=True),
        ),
    ]
