# Generated by Django 4.2.7 on 2024-06-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
