# Generated by Django 4.2.7 on 2024-06-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
