# Generated by Django 4.2.7 on 2024-06-22 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_product_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_number',
            new_name='product_id',
        ),
    ]
