# Generated by Django 4.2.7 on 2024-06-23 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_product_number_product_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='serial',
        ),
    ]
