# Generated by Django 4.2.7 on 2024-06-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_product_product_id_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='serial',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
