# Generated by Django 4.2.7 on 2024-06-23 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_product_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='crypto',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.product')),
                ('video_url', models.FileField(blank=True, null=True, upload_to='crypto/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='dropshiping',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.product')),
                ('video_url', models.FileField(blank=True, null=True, upload_to='dropshiping/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='finance',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.product')),
                ('video_url', models.FileField(blank=True, null=True, upload_to='finance/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Webdev',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.product')),
                ('video_url', models.FileField(blank=True, null=True, upload_to='Webdev/videos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='videos',
        ),
    ]
