# Generated by Django 4.2.7 on 2024-06-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_crypto_dropshiping_finance_webdev_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropshiping',
            name='product',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='product',
        ),
        migrations.RemoveField(
            model_name='webdev',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='serial',
        ),
        migrations.AddField(
            model_name='product',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.DeleteModel(
            name='crypto',
        ),
        migrations.DeleteModel(
            name='dropshiping',
        ),
        migrations.DeleteModel(
            name='finance',
        ),
        migrations.DeleteModel(
            name='Webdev',
        ),
    ]
