# Generated by Django 4.2.7 on 2024-06-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_dropshiping_product_remove_finance_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
