# Generated by Django 4.2.7 on 2024-06-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_product_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bio',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
